site_name: Prisma documentation

theme:
  name: material
  nav_style: dark

  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    primary: black

nav:
  - Home: index.md
  - References:
    - Index: references/index.md
    - OperationResult: references/operation-result-enum.md
    - IMinimalRepository Interface: references/minimal-repository-interface.md
    - IRepository Interface: references/repository-interface.md