site_name: Dolphin documentation

theme:
  name: material
  nav_style: dark
  favicon: assets/images/icon.png
  logo: assets/images/icon.png

  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    primary: black

nav:
  - Home: index.md
  - References: references/index.md